SRCS 		= main.c parser.c \
CC			= cc
RM			= rm -rf
CFLAGS		= -fsanitize=address -g3 -Wall -Wextra -Werror -pthread
NAME		= codexion
CORE_OBJ	= $(CORE_SRC:.c=.o)
OBJS		= $(SRCS:.c=.o)

$(NAME):	$(OBJS) $(CORE_OBJ)
			$(CC) $(CFLAGS) $(OBJS) $(CORE_OBJ) -o $@

all:		
		$(NAME)

clean:		
		$(RM) $(OBJS) $(CORE_OBJ) $(BONUS_OBJS)

fclean:
		clean
		$(RM) $(NAME)

re:		fclean $(NAME)

.PHONY:		all clean fclean re
		
